services:
  oracle:
    image: gvenzl/oracle-free:latest
    container_name: oracle-brico-plus
    env_file:
      - ./.env
    environment:
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "${ORACLE_PORT:-1521}:1521"
      - "${OEM_PORT:-5500}:5500"
    volumes:
      - brico_plus_data:/opt/oracle/oradata
    restart: always

volumes:
  brico_plus_data:
    name: brico_plus_data